# Generated by Django 5.1.6 on 2025-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_deleted_alter_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
